### ISSUE TITLE
Weird error: Couldn't open file for writing

### ISSUE THREAD

**Issue by niklas-ourmachinery** [facebookincubator/FBX2glTF#159]
I'm trying out FBX2glTF on this data set from Nvidia's Open Research Content Archive:

* https://developer.nvidia.com/orca/amazon-lumberyard-bistro

The scene has two FBX files for interior and exterior respectively. Weirdly, the interior FBX converts but the exterior one gives a "Couldn't open file for writing" error:

```
>FBX2glTF-windows-x64.exe Bistro_Research_Interior.fbx
Warning: node /RootNode/Bistro_Research_Interior_CashRegister_01A_Mesh_1134 uses unsupported transform inheritance type 'eInheritRrSs'.
         (Further warnings of this type squelched.)
Wrote 5377537 bytes of glTF to ./Bistro_Research_Interior_out/Bistro_Research_Interior.gltf.
Wrote 38894252 bytes of binary data to ./Bistro_Research_Interior_out/buffer.bin.

>FBX2glTF-windows-x64.exe Bistro_Research_Exterior.fbx
Warning: node /RootNode/Bistro_Research_Exterior__lod0_Glass_3919 uses unsupported transform inheritance type 'eInheritRrSs'.
         (Further warnings of this type squelched.)
ERROR:: Couldn't open file for writing: ./Bistro_Research_Exterior_out/Bistro_Research_Exterior.gltf
```

I wonder if some other error is occurring and it is erroneously being reported as a "Couldn't open file for writing" error, because it makes little sense that it can create one file, but not the other. I've tried the obvious things like using `-o` to specify a different output file name, trying the command in a different directory, etc.

This is on Windows with the latest Windows binary. Any ideas?

**Comment by JernejL** [comment]
I have this problem too - a lot. This happens consistently, and it happens because tool doesn't create the intermediate folders correctly, it checks for file existing in output directory, but when it tries to write image it then sometimes tries to put them into the model.fbm subfolder.. which it never created.
 
You can create the missing folder and that works around the problem. 
 
Same causes probably: bug #109

**Comment by zellski** [comment]
Yeah, this is an old bug. It should be fixed in master (but I will double check). I'm months late to push out a new version –– soon!

**Comment by jbmcgee** [comment]
I built master and still received the same error.

**Comment by zellski** [comment]
I will fix this one way or another, before the next release.

**Comment by yearofthewhopper** [comment]
still not fixed. This error also effected me on high sierra 10.13.6 and mojave

**Comment by zellski** [comment]
Still not fixed with the 0.9.5 release (which would not be surprising since it’s a year old), or with a more recent build?

**Comment by yearofthewhopper** [comment]
I pulled it down yesterday and encountered this error. And also since this is the only precompiled available on https://developers.facebook.com/docs/sharing/3d-posts/glb-tutorials/ that means that this users are encountering this error more even if it’s older. Also re: https://developers.facebook.com/docs/sharing/3d-posts/glb-tutorials/ there’s a typo in the tutorial where the code means to say usr/local/bin but says user/local/bin

**Comment by zellski** [comment]
Thanks. Fixing the FB documentation is important and as it happens I can take care of that.

Can you please be as clear as possible about what you’re running? “Pulled it down yesterday” — from the release pages? From Azure? Or the source, and you built it?

And is the error exactly as above? Or just “this error seems pretty related to this thread?”

**Comment by yearofthewhopper** [comment]
Pulled down the master branch yesterday from GitHub and encountered the “couldn’t open file for writing” error after converting a maya 2019 fbx.

**Comment by zellski** [comment]
Wow. That’s really strange. Thanks, I’ll open this can of worms back up...

**Comment by zellski** [comment]
Wait... it happened on Mac OS X too? Okay, I think that's a different bug (that looks similar). Could you copy-paste precisely your input and output? Or post a screen capture?

**Comment by zellski** [comment]
It **will** of course happen if the tool is asked to write the output file somewhere where you don't have write permission, for example.

**Comment by zellski** [comment]
The original bug has been fixed. @yearofthewhopper, if your troubles persist please file a new issue.

**Comment by jbmcgee** [comment]
Tried converting the bistro model with a bleeding edge [binary](https://ci.appveyor.com/project/Facebook/fbx2gltf/builds/24977245) for windows built with 36aa4428ba80641d2a037064415d389eee7a294b. I received the same error.
